package com.cloakyloki.entity.enumerated;

public enum CardType {
    Artifact,
            Card,
            Conspiracy,
            Creature,
            Dragon,
            Dungeon,
            Eaturecray,
            Elemental,
            Elite,
            Emblem,
            Enchantment,
            Ever,
            Goblin,
            Hero,
            Instant,
            Jaguar,
            Knights,
            Land,
            Phenomenon,
            Plane,
            Planeswalker,
            Scariest,
            Scheme,
            See,
            Sorcery,
            Stickers,
            Summon,
            Token,
            Tribal,
            Universewalker,
            Vanguard,
            Wolf
}
